$(document).ready(function(){
  $(".flip1").click(function(){
    $(".panel1").slideToggle("slow");
  });
  $(".flip2").click(function(){
    $(".panel2").slideToggle("slow");
  });
  $(".flip3").click(function(){
    $(".panel3").slideToggle("slow");
  });
  $(".flip4").click(function(){
    $(".panel4").slideToggle("slow");
  });
  $(".flip5").click(function(){
    $(".panel5").slideToggle("slow");
  });
  $(".flip6").click(function(){
    $(".panel6").slideToggle("slow");
  });
  $(".flip7").click(function(){
    $(".panel7").slideToggle("slow");
  });
  $(".flip8").click(function(){
    $(".panel8").slideToggle("slow");
  });
  $(".flip9").click(function(){
    $(".panel9").slideToggle("slow");
  });
  $(".flip10").click(function(){
    $(".panel10").slideToggle("slow");
  });
  $(".flip11").click(function(){
    $(".panel12").slideToggle("slow");
  });

});
